### ISSUE TITLE
how to get correct rotated image after capturing from camera

### ISSUE THREAD

**Issue by nishu3389** [Dhaval2404/ImagePicker#203] opened 2021-05-18 09:57 UTC
Getting rotated image when capturing from camera, any solution of that??

**Comment by Dhaval2404** [comment] 2021-05-19 08:33
@nishu3389 I will investigate the issue. Can you please provide more info to reproduce the issue? Like the android version and device info on which you perform the testing.

**Comment by rrsaikat** [comment] 2021-05-24 13:43
@Dhaval2404 
Scenario: Lets you have three imageview! 1st and 2nd works fine. But for 3rd, captured Image gets **Anticlockwise** after setting into imageview!

Device: Redmi note 5 pro
OS: Android 8.1

**Comment by nishu3389** [comment] 2021-05-25 06:50
Device: Redmi note 5 pro
OS: Android 9

Please use exif interface to get the correct orientation of the captured image,
So the developer dont have to do it every time he use your library.
Anyway great work you have done, just correct issue.

**Comment by Dhaval2404** [comment] 2021-05-28 16:37
Duplicate of #56

**Closed by Dhaval2404** 2021-05-28 16:37 UTC
