### ISSUE TITLE
can we choose multiple images at one time from gallery ?

### ISSUE THREAD

**Issue by rinathakkar** [Dhaval2404/ImagePicker#172] opened 2021-02-25 07:21 UTC

**Comment by hitesh-dhamshaniya** [comment] 2021-02-25 13:12
@rinathakkar I think this is an enhancement, not an issue. Kindly check for a single image and if you come across with crash/bug, report it, with an error stack trace. Thank you.

**Comment by lmj0011** [comment] 2021-03-07 02:27
@rinathakkar [this fork](https://github.com/Harmanbeer007/ImagePicker/commits/master) seems to have implemented this

**Comment by rinathakkar** [comment] 2021-03-09 11:42
@lmj0011 Thank you

**Comment by Dhaval2404** [comment] 2021-05-23 12:04
Duplicate of #3

**Closed by Dhaval2404** 2021-05-23 12:04 UTC
