### ISSUE TITLE
onActivityResult: ImagePicker Error: Camera app not found

### ISSUE THREAD

**Issue by denite** [Dhaval2404/ImagePicker#197] opened 2021-05-03 15:57 UTC
## Summary
Camera app does not open.
Error:  onActivityResult: ImagePicker Error: Camera app not found

## Code to reproduce

 ImagePicker.with(mainActivity)
                .cameraOnly()
                .crop(245f, 150f)
                .maxResultSize(1500, 918)
                .compress(200)
                .saveDir(imageFolderPath)
                .start(IMAGE_RESULT)

## Android version
Android 11

## Impacted devices
One Plus 7 Pro

## Installation method
Gradle 

## SDK version
1.8
targetSdkVersion 30

## Other information
Gallery picker works great - just the camera won't open at all.

**Comment by Dhaval2404** [comment] 2021-05-15 06:15
Duplicate of #162

**Closed by Dhaval2404** 2021-05-15 06:15 UTC
