### ISSUE TITLE
select multiple images

### ISSUE THREAD

**Issue by dekanako** [Dhaval2404/ImagePicker#84] opened 2020-05-12 10:20 UTC
Hey can I select multiple images with the library ?

**Comment by Dhaval2404** [comment] 2020-05-12 12:31
@dekanako No, This feature is not supported!

**Comment by dekanako** [comment] 2020-05-13 01:05
Thank you

**Comment by Dhaval2404** [comment] 2020-07-11 17:00
Duplicate of #3

**Closed by Dhaval2404** 2020-07-11 17:00 UTC
Labels: duplicate

**Comment by royinfoware** [comment] 2022-05-16 05:17
is this This feature is supported now?
