### ISSUE TITLE
Translate text

### ISSUE THREAD

**Issue by rafaelkowal** [Dhaval2404/ImagePicker#45] opened 2019-12-02 19:39 UTC
Is there any way to translate edit photo title text and alert choose?

**Comment by Dhaval2404** [comment] 2019-12-03 18:54
@rafaelkowal  Please refer #17 for more information.

Let me know if you need any more help.

**Comment by Dhaval2404** [comment] 2020-01-06 18:29
Duplicate of #17

**Closed by Dhaval2404** 2020-01-06 18:29 UTC
