### ISSUE TITLE
using .crop doesn't work corectly

### ISSUE THREAD

**Issue by DevTard** [Dhaval2404/ImagePicker#32] opened 2019-09-20 14:20 UTC
When using .crop, it opens the camera, when you take a picture it opens the crop screen and opens the camera again.

**Comment by stanislavmilev5** [comment] 2020-02-03 14:36
I have the same issue, can you please provide a fix

**Comment by vitorhugods** [comment] 2020-02-11 14:22
This seems to be device dependent. Or more specifically, dependent on the Camera App.
It is happening to me as well in the Android Emulator (29.3.7), but it does not happen on my LG G8S.

**Comment by vitorhugods** [comment] 2020-02-27 13:30
After further investigation:

It only happens in a few devices (maybe it is Android 10+ related), and *only* when using InlineActivityResult.

I replaced InlineActivityResult with the old-fashioned approach, and it worked flawlessly.

**Comment by Dhaval2404** [comment] 2020-04-11 14:56
The issue is in InlineActivityResult lib. I have submitted a [pull request (https://github.com/florent37/InlineActivityResult/pull/13), Which is recently merged in their master branch.

**Comment by Dhaval2404** [comment] 2020-07-12 18:42
[Pull Request](https://github.com/florent37/InlineActivityResult/pull/13) has been merged, So upgrading Gradle for the fixes.

**Closed** 2020-07-13 19:04 UTC
