### ISSUE TITLE
[Request Features] Add mutiple image selection from gallery

### ISSUE THREAD

**Issue by ashishgupta-kiwi** [Dhaval2404/ImagePicker#131] opened 2020-10-15 06:16 UTC
Hi Please add this feature

**Comment by rommansabbir** [comment] 2020-10-25 12:48
For client requirement purpose, I'm using this library. It would be better if provide mutilple image seclection with crop feature.

**Comment by Dhaval2404** [comment] 2020-12-19 13:42
Duplicate of #3

**Closed by Dhaval2404** 2020-12-19 13:42 UTC
