### ISSUE TITLE
Free crop without choosing the predefined crop ratios

### ISSUE THREAD

**Issue by reynoshsunny** [Dhaval2404/ImagePicker#70] opened 2020-04-06 17:25 UTC
Hello @Dhaval2404 .
I think currently there is no option for the free crop(drag the ends of the crop frame without selecting the predefined crop ratios). If it is there it would be better.
Thanks.

**Comment by Dhaval2404** [comment] 2020-04-06 17:29
@reynoshsunny This is a very good suggestion. As of now cropping is handled by 3rd party lib uCrop and they are not supporting this feature.

**Comment by Dhaval2404** [comment] 2021-05-28 16:28
Duplicate of #76

**Closed by Dhaval2404** 2021-05-28 16:28 UTC
