### ISSUE TITLE
Images clicked in portrait mode are rotated.

### ISSUE THREAD

**Issue by kundank191** [Dhaval2404/ImagePicker#24] opened 2019-08-01 15:46 UTC
When I take a picture from the camera in portrait mode the picture gets rotated. When the picture is taken by the camera in landscape mode the picture doesn't get rotated and looks the way it was clicked.

**Comment by Dhaval2404** [comment] 2019-08-02 04:16
@kundank191 Thanks for the update. Will take a look.

**Comment by siltaz** [comment] 2019-10-31 05:53
yup i'm having the same issue. Picture from camera gets rotated and croped on Capture.

**Comment by zeebikenav** [comment] 2020-01-13 17:23
Im having the same issue also

**Comment by makkhay** [comment] 2020-02-05 01:09
I think this bug is an Android framework bug. I was working on retrieving URI after picking the image and I was facing the same issue. The weird part is, it only does that for pictures taken from camera.

**Comment by khizarhayat** [comment] 2021-05-16 15:51
Used .cropSquare() as quick solution.

**Comment by Dhaval2404** [comment] 2021-05-28 16:36
Duplicate of #56

**Closed by Dhaval2404** 2021-05-28 16:36 UTC
