### ISSUE TITLE
Two Much Needed Features: Free Hand Cropper, To open the actual Gallery Directly/ from files. 

### ISSUE THREAD

**Issue by CatalystMonish** [Dhaval2404/ImagePicker#147] opened 2020-12-29 18:07 UTC
Thanks, Dhaval for creating this amazing library it works well for my use, the imagine compression is too good, just I feel like these two important features are missing from this it would be helpful if you look into adding it, if I get some free time I'll work on it and submit a pull request.

**Comment by Dhaval2404** [comment] 2021-05-28 16:21
Duplicate of #87 #76

**Closed by Dhaval2404** 2021-05-28 16:21 UTC
