### ISSUE TITLE
Can you add free hand cropping ?

### ISSUE THREAD

**Issue by EleshBaraiya** [Dhaval2404/ImagePicker#112] opened 2020-08-18 09:08 UTC
I want to freehand cropping so need to just add one line codding in your code setFreeStyleCropEnabled(true)

**Comment by Dhaval2404** [comment] 2021-05-28 16:22
Duplicate of #76

**Closed by Dhaval2404** 2021-05-28 16:22 UTC

**Comment by maleeqB** [comment] 2024-12-25 00:58
How is this supposed to be a duplicate? UCrop is still being used by this library and UCrop#Options support setFreeStyleCropEnabled(boolean)



no such way to own CropProvider, UCrop options or anything
