### ISSUE TITLE
unnecessary WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by kuadam** [Dhaval2404/ImagePicker#153] opened 2021-01-14 08:29 UTC
I am using internal app storage. Is there any way to remove WRITE_EXTERNAL_STORAGE request (1.8 version)?

**Comment by Dhaval2404** [comment] 2021-05-15 06:36
Storage permission will be removed from v2.0

Duplicate of #29

**Closed by Dhaval2404** 2021-05-15 06:36 UTC
