### ISSUE TITLE
multiple image selection

### ISSUE THREAD

**Issue by Zia-Sheikh** [Dhaval2404/ImagePicker#178] opened 2021-03-12 13:23 UTC
hello first of all I am very thankful for this life saving work, but I couldn't understand that how to select multiple images from gallery? I already seen #172 but couldn't understand. Please guide, your help would be much appreciated.
**Thank you.**

**Comment by lmj0011** [comment] 2021-03-15 14:40
You're going to have to try seeing if there's a fork with that feature implemented and try it out by importing it into your project

Here's a fork: https://github.com/Harmanbeer007/ImagePicker

Here's some S/O answers to get you on the right path for adding it to your project: https://stackoverflow.com/a/38848119/2445763

also see: https://github.com/Dhaval2404/ImagePicker/issues/3#issuecomment-792175988

I'm using [a similar library](https://github.com/kroegerama/bottomsheet-imagepicker) in one of my projects, and just like this one multiple image selection is not a feature. I'm busy with other projects currently, hence why I haven't already tried this one out myself. However, I am interested to see if that fork actually has the multiple image selection working

**Comment by Dhaval2404** [comment] 2021-05-23 12:05
@Zia-Sheikh This feature is not supported yet.

Duplicate of #3

**Closed by Dhaval2404** 2021-05-23 12:05 UTC
