### ISSUE TITLE
Receiving "Failed To Create Camera Image File"

### ISSUE THREAD

**Issue by IronDigitalMedia** [Dhaval2404/ImagePicker#44] opened 2019-12-01 20:04 UTC
`
2019-12-01 14:00:05.865 16921-16921/com.irondigitalmedia.keep W/System.err:     at com.github.dhaval2404.imagepicker.util.FileUtil.getImageFile(FileUtil.kt:46)

2019-12-01 14:00:05.865 16921-16921/com.irondigitalmedia.keep W/System.err:     at com.github.dhaval2404.imagepicker.util.FileUtil.getImageFile$default(FileUtil.kt:30)

2019-12-01 14:00:05.865 16921-16921/com.irondigitalmedia.keep W/System.err:     at com.github.dhaval2404.imagepicker.provider.CameraProvider.startCameraIntent(CameraProvider.kt:86)

2019-12-01 14:00:05.865 16921-16921/com.irondigitalmedia.keep W/System.err:     at com.github.dhaval2404.imagepicker.provider.CameraProvider.checkPermission(CameraProvider.kt:72)

2019-12-01 14:00:05.865 16921-16921/com.irondigitalmedia.keep W/System.err:     at com.github.dhaval2404.imagepicker.provider.CameraProvider.startIntent(CameraProvider.kt:61)

2019-12-01 14:00:05.865 16921-16921/com.irondigitalmedia.keep W/System.err:     at com.github.dhaval2404.imagepicker.ImagePickerActivity.loadBundle(ImagePickerActivity.kt:68)

2019-12-01 14:00:05.865 16921-16921/com.irondigitalmedia.keep W/System.err:     at com.github.dhaval2404.imagepicker.ImagePickerActivity.onCreate(ImagePickerActivity.kt:47)`

Your code says this shouldn't ever happen. 

else -> {
                Log.e(TAG, "Image provider can not be null")
                // Something went Wrong! This case should never happen
                setError(getString(R.string.error_task_cancelled))
            }

line 72. I'm not sure what's going on. Would you need anything else to help figure out what's going on? The permission is given i checked the app permissions it settings. 

This works great on a physical device (note 9), but doesn't work on a virtual device.

**Comment by Dhaval2404** [comment] 2019-12-03 18:51
Possible duplicate of #38

**Closed** 2019-12-17 18:04 UTC
