### ISSUE TITLE
Plugin not worked with letest Android version(10).

### ISSUE THREAD

**Issue by ankitkanojia** [Dhaval2404/ImagePicker#47] opened 2019-12-11 08:43 UTC
Library Works perfectly in the lower version but not work as expected with the latest version.

By the way good work, This Library helps me a lot.

Thank you.

**Comment by Dhaval2404** [comment] 2019-12-13 07:01
Possible Duplicate of #38

**Comment by Dhaval2404** [comment] 2019-12-13 07:01
@ankitkanojia Have you tried to set android:requestLegacyExternalStorage="true" in the android manifest. It's a must for API 29.

![68088859-1bafee00-fe89-11e9-81eb-e17b0d823bfc](https://user-images.githubusercontent.com/7314181/70776887-66842600-1da4-11ea-8287-2555da386c8f.png)

**Closed** 2019-12-13 08:20 UTC
