### ISSUE TITLE
Free Crop and Big size images loads slow

### ISSUE THREAD

**Issue by vedraj360** [Dhaval2404/ImagePicker#191] opened 2021-04-14 10:41 UTC
Free Crop and Big size images loads slow

## Summary
1. The current crop library is good but lacks the one of the important feature Free crop like drag square to crop image. You can try to use https://github.com/ArthurHub/Android-Image-Cropper can provide the option to select the crop library.

2. On some phones when photo is clicked and size of image is Big then it take time to get the result in callback.

**Comment by Dhaval2404** [comment] 2021-05-28 16:24
Duplicate of #76 #139

**Closed by Dhaval2404** 2021-05-28 16:24 UTC
